# -*- coding: utf-8 -*-
"""LINEbot練習.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12PXOozQ6ahIh9y88jivA2XB9EGPmrvp9
"""

# 全体の流れ
# ①コードを書く("Talk API"とLINEDeveloperの"Channel secret"を取得してから)
# ②ローカルリポジトリを作成する
# ③Githubのリモートリポジトリにローカルリポジトリを送る
# ④HerokuとGithubを連携する
# ⑤LINE DeveloperのWebhookにHerokuのデプロイしたURLを貼り付ける
# ⑥URLにデコレータの”/callback”を追記する

from flask import Flask,request,abort
from linebot import LineBotApi,WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent,TextMessage,TextSendMessage
from linebot.models.events import FollowEvent
import pya3rt

app=Flask(__name__)


linebot_api=LineBotApi('XiNhvqTfoOHWOst12UQRE7fo9DQD7y+ZJlq88AMk5gBdmS89qwnYKxq5m6wx1vQlD4nonbeFjQZsL9GHdv3pGn6JMi8Ak45SXzObxD6pCO/+IdoxTtDZ8FAJSPLB9JMFLfFjdUE7fZNJTCKqsxKz3gdB04t89/1O/w1cDnyilFU=')

handler=WebhookHandler('c048aa8a0dc75dd3924e2b2878d321cb')

@app.route("/callback",methods=['POST'])
def callback():
    signature=request.headers["X-Line-Signature"]
    body=request.get_data(as_text=True)

    try:
        handler.handle(body,signature)
    except InvalidSignatureError:
        abort(400)
    
    return 'OK'

@handler.add(MessageEvent,message=TextMessage)
def handle_message(event):
    ai_message=talk(event.message.text)
    linebot_api.reply_message(event.reply_token,TextSendMessage(text=ai_message))

@handler.add(FollowEvent)
def handle_follow(event):
    linebot_api.reply_message(event.reply_token,TextSendMessage(text=
        'はじめまして！登録ありがとうございます！こちらはAIと気軽に話せるチャンネルとなっております。何か話しかけてみてください！'
    ))

def talk(call):
    apikey="DZZeqgnJIzeGIsw8UxnAAfog2qp8B6Qm"
    client=pya3rt.TalkClient(apikey)
    reply=client.talk(call)
    return reply['results'][0]['reply']

if __name__=='__main__':
    app.run()

